export const AFFILIATE = {
  ADVANCE_AUTO:   'https://www.advanceautoparts.com',
  AUTOZONE:       'https://www.autozone.com',
  AMAZON:         'https://www.amazon.com/?tag=poolcoach06-20',
  TIRE_RACK:      'https://www.tirerack.com',
  SIMPLE_TIRE:    'https://www.simpletire.com',
  MAVIS:          'https://www.mavistire.com',
  VALVOLINE:      'https://www.valvoline.com',
  SAFELITE:       'https://www.safelite.com',
  EDMUNDS:        'https://www.edmunds.com',
  AAA:            'https://www.aaa.com',
  CHEMICAL_GUYS:  'https://www.chemicalguys.com',
  FINDITPARTS:    'https://www.finditparts.com',
  AUTONATION:     'https://parts.autonation.com',
  BATTERY_TENDER: 'https://www.batterytender.com',
  EASTWOOD:       'https://www.eastwoodco.com',
  UPSIDE:         'https://upside.com',
  ATOB:           'https://atob.com',
  REPAIRPAL:      'https://repairpal.com',
};