export const AFFILIATE = {
  AUTOZONE:       'https://www.autozone.com',
  AMAZON:         'https://www.amazon.com/?tag=autocoach06-20',
  SIMPLE_TIRE:    'https://www.simpletire.com',
  MAVIS:          'https://www.kqzyfj.com/click-101879486-15764585?sid=autocoach_app_tires',
  PARTSGEEK:      'https://www.anrdoezrs.net/click-101879486-13699760?sid=autocoach_app_parts_general',
  VALVOLINE:      'https://www.valvoline.com',
  SAFELITE:       'https://www.safelite.com',
  EDMUNDS:        'https://www.edmunds.com',
  AAA:            'https://www.aaa.com',
  CHEMICAL_GUYS:  'https://www.chemicalguys.com',
  FINDITPARTS:    'https://www.finditparts.com',
  AUTONATION:     'https://parts.autonation.com',
  BATTERY_TENDER: 'https://www.batterytender.com',
  EASTWOOD:       'https://www.eastwoodco.com',
  UPSIDE:         'https://upside.com',
  ATOB:           'https://atob.com',
  REPAIRPAL:      'https://repairpal.com',
};